### ISSUE TITLE
NO MORE UPDATES

### ISSUE THREAD

**Issue by daye10** [daye10/smile#15]
I do not think that I will be updating the bot for next months if there is a big update with API restructuration, since I'm back to school. Also I'm working on others projects that would be much much bigger and well structured. 

So be aware if you want to subscribe for premium, there's no guarantee that I will update the bot if  game changes a lot, I can handle minors updates, but not the big ones from Akatsuki.

That being said, thanks for using the bot and supporting the work, appreciate it.

**Comment by Jacorella** [comment]
is it possible to have the source code?

**Comment by daye10** [comment]
I do not think that I’m allowed to share it since the program communicates with a private API and it contains privates keys, it’s probably against the ToS. But you can find an old open source version in the README, if you really want to.

**Comment by daye10** [comment]
> is it possible to have the source code?

I do not think that I’m allowed to share it since the program communicates with a private API and it contains privates keys, it’s probably against the ToS. But you can find an old open source version in the README, if you really want to.

**Comment by Jacorella** [comment]
Thank you for your answer. I tried to create my own bot but one thing I still don't understand is how to get the User ID and password of basic authentication :c
![BASIC](https://user-images.githubusercontent.com/82755553/212961078-10b0643d-c272-4d94-aac4-26e903ff59a0.png)

**Comment by daye10** [comment]
join the server and dm I’ll try to help you as much as I can
