### ISSUE TITLE
Banned for no reason.

### ISSUE THREAD

**Issue by yousefh23** [daye10/smile#30]
Hi there, I was banned from the discord and I'm not sure why. I didn't do anything and was removed out of nowhere. Can you help me resolve this please?

**Comment by yousefh23** [comment]
I was going to pay for dokkan plus when I went in and realized I was banned and I didn't do anything/break any rules

**Comment by daye10** [comment]
You’re banned because you’re dming people trying to sell accounts in the discord server without even supporting the work, and to me it is disrespectful. I will unban you but don’t dm people in the server to sell accounts. There are many platforms for that

**Comment by yousefh23** [comment]
sounds good sorry about that. Will do
